import datetime
import random

def generate_sql():
    sql_statements = []

    # Constants
    BASE_DATE = datetime.datetime(2026, 2, 1) # Start from Feb 1st, 2026
    DAYS_TO_GENERATE = 20 # Generate 20 days of data
    
    # 1. Clean up old test data (Using specific IDs to be safe)
    sql_statements.append("-- Cleanup old test data")
    sql_statements.append("DELETE FROM `electricity_data_item` WHERE `remark` = 'AutoGeneratedTest';")
    sql_statements.append("DELETE FROM `alarm` WHERE `remark` = 'AutoGeneratedTest';")
    sql_statements.append("DELETE FROM `device` WHERE `id` LIKE 'dev-demo-%';")
    sql_statements.append("DELETE FROM `device_type` WHERE `id` = 'dt-demo-inv';")
    sql_statements.append("DELETE FROM `power_station` WHERE `id` LIKE 'ps-demo-%';")
    sql_statements.append("\n")

    # 2. Insert Power Stations (3 Stations)
    stations = [
        {'id': 'ps-demo-01', 'code': 'PS_DEMO_01', 'name': '北京大兴示范电站', 'capacity': 1.2, 'loc_x': 116.3, 'loc_y': 39.9},
        {'id': 'ps-demo-02', 'code': 'PS_DEMO_02', 'name': '上海浦东分布式电站', 'capacity': 0.8, 'loc_x': 121.5, 'loc_y': 31.2},
        {'id': 'ps-demo-03', 'code': 'PS_DEMO_03', 'name': '广州天河屋顶光伏', 'capacity': 0.5, 'loc_x': 113.3, 'loc_y': 23.1}
    ]

    sql_statements.append("-- Insert Power Stations")
    for s in stations:
        sql = f"INSERT INTO `power_station` VALUES ('{s['id']}', NULL, '{s['code']}', '{s['name']}', {s['capacity']}, 100.00, 380.00, {s['loc_x']}, {s['loc_y']}, NULL, NULL, NOW(), 'admin', NOW(), 'admin', 1, 103);"
        sql_statements.append(sql)
    sql_statements.append("\n")

    # 3. Insert Device Type
    sql_statements.append("-- Insert Device Type")
    sql_statements.append("INSERT INTO `device_type` VALUES ('dt-demo-inv', '逆变器', 'Inverter', '测试逆变器类型', 'admin', NOW(), 'admin', NOW());")
    sql_statements.append("\n")

    # 4. Insert Devices (2 per station)
    devices = []
    sql_statements.append("-- Insert Devices")
    dev_counter = 1
    for s in stations:
        for i in range(1, 3): # 2 devices per station
            dev_id = f"dev-demo-{dev_counter:02d}"
            dev_name = f"{s['name']}-逆变器#{i}"
            dev_code = f"INV_DEMO_{dev_counter:02d}"
            devices.append({'id': dev_id, 'code': dev_code, 'station_id': s['id']})
            
            sql = f"INSERT INTO `device` VALUES ('{dev_id}', '{s['id']}', '{dev_code}', '{dev_name}', 'dt-demo-inv', 50.00, '华为', 50.00, '低压并网', NULL, 0, NULL, NOW(), 'admin', NOW(), 'admin', 1, 103);"
            sql_statements.append(sql)
            dev_counter += 1
    sql_statements.append("\n")

    # 5. Insert Electricity Data (Generation Data)
    # Generate 3 records per day (Peak, Flat, Valley) for each device
    # Peak: 08:00 - 12:00, Flat: 12:00 - 18:00, Valley: 18:00 - 22:00 (Rough approx)
    sql_statements.append("-- Insert Electricity Generation Data (Over 100 rows)")
    
    # Prices
    price_map = {'peak': 1.2, 'flat': 0.8, 'valley': 0.4}
    
    for day_offset in range(DAYS_TO_GENERATE):
        current_date = BASE_DATE + datetime.timedelta(days=day_offset)
        date_str = current_date.strftime('%Y-%m-%d')
        
        for dev in devices:
            # Random fluctuation
            efficiency = random.uniform(0.8, 1.0)
            
            # --- Peak Period (08:00 - 11:00) ---
            kwh = round(random.uniform(30, 50) * efficiency, 2)
            cost = round(kwh * price_map['peak'], 2)
            sql = f"INSERT INTO `electricity_data_item` (`device_id`, `data_time`, `type`, `begin_time`, `end_time`, `value`, `cost`, `price`, `remark`, `create_time`, `create_by`) VALUES ('{dev['id']}', '{date_str} 08:00:00', 'peak', '{date_str} 08:00:00', '{date_str} 11:00:00', {kwh}, {cost}, {price_map['peak']}, 'AutoGeneratedTest', NOW(), 'admin');"
            sql_statements.append(sql)

            # --- Flat Period (11:00 - 16:00) ---
            kwh = round(random.uniform(50, 80) * efficiency, 2) # Higher generation at noon
            cost = round(kwh * price_map['flat'], 2)
            sql = f"INSERT INTO `electricity_data_item` (`device_id`, `data_time`, `type`, `begin_time`, `end_time`, `value`, `cost`, `price`, `remark`, `create_time`, `create_by`) VALUES ('{dev['id']}', '{date_str} 12:00:00', 'flat', '{date_str} 11:00:00', '{date_str} 16:00:00', {kwh}, {cost}, {price_map['flat']}, 'AutoGeneratedTest', NOW(), 'admin');"
            sql_statements.append(sql)

            # --- Valley Period (16:00 - 20:00) ---
            kwh = round(random.uniform(10, 30) * efficiency, 2) # Low generation evening
            cost = round(kwh * price_map['valley'], 2)
            sql = f"INSERT INTO `electricity_data_item` (`device_id`, `data_time`, `type`, `begin_time`, `end_time`, `value`, `cost`, `price`, `remark`, `create_time`, `create_by`) VALUES ('{dev['id']}', '{date_str} 18:00:00', 'valley', '{date_str} 16:00:00', '{date_str} 20:00:00', {kwh}, {cost}, {price_map['valley']}, 'AutoGeneratedTest', NOW(), 'admin');"
            sql_statements.append(sql)
    
    sql_statements.append("\n")

    # 6. Insert Alarms (Random Alarms)
    sql_statements.append("-- Insert Alarm Data")
    alarm_codes = ['E001', 'E002', 'W001']
    alarm_descs = ['Inverter Grid Voltage High', 'Inverter Temperature High', 'Communication Interruption']
    alarm_levels = [1, 2, 3]
    
    for i in range(10): # 10 random alarms
        dev = random.choice(devices)
        day_offset = random.randint(0, DAYS_TO_GENERATE-1)
        alarm_time = BASE_DATE + datetime.timedelta(days=day_offset, hours=random.randint(9, 17))
        time_str = alarm_time.strftime('%Y-%m-%d %H:%M:%S')
        
        idx = random.randint(0, 2)
        
        # ID generation is tricky without auto-increment knowledge, assuming UUID or String.
        # Based on other IDs (ps-test-01), likely string.
        options = "0123456789abcdef"
        alarm_id = "alarm-" + "".join(random.choice(options) for _ in range(8))
        
        sql = f"INSERT INTO `alarm` (`id`, `device_code`, `err_code`, `error_description`, `level`, `status`, `data_time`, `remark`, `image_url`) VALUES ('{alarm_id}', '{dev['code']}', '{alarm_codes[idx]}', '{alarm_descs[idx]}', '{alarm_levels[idx]}', '1', '{time_str}', 'AutoGeneratedTest', NULL);"
        sql_statements.append(sql)

    return "\n".join(sql_statements)

if __name__ == "__main__":
    print(generate_sql())
