
import datetime
import random
from pathlib import Path

def generate_sql():
    target_end_date = datetime.datetime(2026, 3, 31)
    random.seed(20260331)

    # Open file for writing directly
    with open('mock-data/init_large_test_data.sql', 'w', encoding='utf-8') as f, \
        open('mock-data/init_large_alarm_only.sql', 'w', encoding='utf-8') as af:
        
        def write_sql(s):
            f.write(s)

        def write_alarm_sql(s):
            af.write(s)

        # Header: Set charset and cleanup
        write_sql("SET NAMES utf8mb4;\n")
        write_sql("-- Cleanup old test data\n")
        write_sql("DELETE FROM `electricity_data_item` WHERE `remark` = 'AutoGeneratedTest';\n")
        write_sql("DELETE FROM `data_item` WHERE `remark` = 'AutoGeneratedTest';\n")
        write_sql("DELETE FROM `alarm` WHERE `remark` = 'AutoGeneratedTest';\n")
        write_sql("DELETE FROM `device` WHERE `id` LIKE 'dev-demo-%';\n")
        write_sql("DELETE FROM `device_type` WHERE `id` = 'dt-demo-inv';\n")
        write_sql("DELETE FROM `power_station` WHERE `id` LIKE 'ps-demo-%';\n\n")

        # 1. Power Stations (12 stations)
        stations = [
            {'id': 'ps-demo-01', 'code': 'PS_DEMO_01', 'name': '北京大兴示范电站', 'capacity': 1.2, 'loc_x': 116.3, 'loc_y': 39.9},
            {'id': 'ps-demo-02', 'code': 'PS_DEMO_02', 'name': '上海浦东分布式电站', 'capacity': 0.8, 'loc_x': 121.5, 'loc_y': 31.2},
            {'id': 'ps-demo-03', 'code': 'PS_DEMO_03', 'name': '广州天河屋顶光伏', 'capacity': 0.5, 'loc_x': 113.3, 'loc_y': 23.1},
            {'id': 'ps-demo-04', 'code': 'PS_DEMO_04', 'name': '深圳南山科技园电站', 'capacity': 1.5, 'loc_x': 113.9, 'loc_y': 22.5},
            {'id': 'ps-demo-05', 'code': 'PS_DEMO_05', 'name': '成都高新区光伏', 'capacity': 0.9, 'loc_x': 104.0, 'loc_y': 30.6},
            {'id': 'ps-demo-06', 'code': 'PS_DEMO_06', 'name': '武汉光谷太阳能', 'capacity': 1.1, 'loc_x': 114.4, 'loc_y': 30.5},
            {'id': 'ps-demo-07', 'code': 'PS_DEMO_07', 'name': '西安高新光伏电站', 'capacity': 1.0, 'loc_x': 108.9, 'loc_y': 34.3},
            {'id': 'ps-demo-08', 'code': 'PS_DEMO_08', 'name': '南京江北新区电站', 'capacity': 0.95, 'loc_x': 118.8, 'loc_y': 32.1},
            {'id': 'ps-demo-09', 'code': 'PS_DEMO_09', 'name': '杭州滨江示范电站', 'capacity': 1.05, 'loc_x': 120.2, 'loc_y': 30.3},
            {'id': 'ps-demo-10', 'code': 'PS_DEMO_10', 'name': '郑州航空港电站', 'capacity': 0.88, 'loc_x': 113.6, 'loc_y': 34.8},
            {'id': 'ps-demo-11', 'code': 'PS_DEMO_11', 'name': '济南新旧动能电站', 'capacity': 0.92, 'loc_x': 117.1, 'loc_y': 36.7},
            {'id': 'ps-demo-12', 'code': 'PS_DEMO_12', 'name': '重庆两江新区电站', 'capacity': 1.18, 'loc_x': 106.6, 'loc_y': 29.6}
        ]
        
        write_sql("-- Insert Power Stations\n")
        for s in stations:
            write_sql(f"INSERT INTO `power_station` VALUES ('{s['id']}', NULL, '{s['code']}', '{s['name']}', {s['capacity']}, 100.00, 380.00, {s['loc_x']}, {s['loc_y']}, NULL, NULL, NOW(), 'admin', NOW(), 'admin', 1, 103);\n")
        write_sql("\n")

        # 2. Device Type
        write_sql("-- Insert Device Type\n")
        write_sql("INSERT INTO `device_type` VALUES ('dt-demo-inv', '逆变器', 'Inverter', '测试逆变器类型', 'admin', NOW(), 'admin', NOW());\n\n")

        # 3. Devices
        write_sql("-- Insert Devices\n")
        devices = []
        dev_counter = 1
        for s in stations:
            for i in range(1, 4): # 3 devices per station
                dev_id = f"dev-demo-{dev_counter:02d}"
                dev_name = f"{s['name']}-逆变器#{i}"
                dev_code = f"INV_DEMO_{dev_counter:02d}"
                devices.append({'id': dev_id, 'code': dev_code, 'station_id': s['id']})
                
                write_sql(f"INSERT INTO `device` VALUES ('{dev_id}', '{s['id']}', '{dev_code}', '{dev_name}', 'dt-demo-inv', 50.00, '华为', 50.00, '低压并网', NULL, 0, NULL, NOW(), 'admin', NOW(), 'admin', 1, 103);\n")
                dev_counter += 1
        write_sql("\n")

        # 4. Electricity Data (Yearly + Monthly + Daily + Hourly)
        write_sql("-- Insert Electricity Generation Data\n")
        # Update: Map 'sharp' to 'tip' to match Java Enum
        price_map = {'tip': 1.5, 'peak': 1.2, 'flat': 0.8, 'trough': 0.4, 'deep': 0.2}
        
        # Generate from Jan 1, 2025 to Mar 31, 2026
        start_date = datetime.datetime(2025, 1, 1)
        
        monthly_data = {} # { (device_id, year_month): total_kwh }
        yearly_data = {}  # { (device_id, year): total_kwh }

        total_days = (target_end_date - start_date).days + 1
        for day_offset in range(total_days):
            current_date = start_date + datetime.timedelta(days=day_offset)
            date_str = current_date.strftime('%Y-%m-%d')
            year_month = current_date.strftime('%Y-%m')
            year_str = current_date.strftime('%Y')

            # Simulate seasonality (Summer higher, Winter lower)
            month = current_date.month
            season_factor = 1.0
            if 5 <= month <= 8: season_factor = 1.3
            elif 11 <= month <= 2: season_factor = 0.7

            for dev in devices:
                dev_day_total = 0.0
                efficiency = random.uniform(0.8, 1.0) * season_factor
                
                # 5 Time Periods per day
                # 1. Deep Valley (00:00 - 06:00)
                kwh = round(random.uniform(5, 10) * efficiency, 2)
                cost = round(kwh * price_map['deep'], 2)
                dev_day_total += kwh
                write_sql(f"INSERT INTO `electricity_data_item` (`device_id`, `data_time`, `type`, `begin_time`, `end_time`, `value`, `cost`, `price`, `remark`, `create_time`, `create_by`) VALUES ('{dev['id']}', '{date_str} 02:00:00', 'deep', '{date_str} 00:00:00', '{date_str} 06:00:00', {kwh}, {cost}, {price_map['deep']}, 'AutoGeneratedTest', NOW(), 'admin');\n")

                # 2. Trough/谷 (06:00 - 08:00)
                kwh = round(random.uniform(10, 15) * efficiency, 2)
                cost = round(kwh * price_map['trough'], 2)
                dev_day_total += kwh
                write_sql(f"INSERT INTO `electricity_data_item` (`device_id`, `data_time`, `type`, `begin_time`, `end_time`, `value`, `cost`, `price`, `remark`, `create_time`, `create_by`) VALUES ('{dev['id']}', '{date_str} 07:00:00', 'trough', '{date_str} 06:00:00', '{date_str} 08:00:00', {kwh}, {cost}, {price_map['trough']}, 'AutoGeneratedTest', NOW(), 'admin');\n")

                # 3. Flat (08:00 - 10:00) & (14:00 - 18:00)
                kwh = round(random.uniform(20, 40) * efficiency, 2)
                cost = round(kwh * price_map['flat'], 2)
                dev_day_total += kwh
                write_sql(f"INSERT INTO `electricity_data_item` (`device_id`, `data_time`, `type`, `begin_time`, `end_time`, `value`, `cost`, `price`, `remark`, `create_time`, `create_by`) VALUES ('{dev['id']}', '{date_str} 16:00:00', 'flat', '{date_str} 14:00:00', '{date_str} 18:00:00', {kwh}, {cost}, {price_map['flat']}, 'AutoGeneratedTest', NOW(), 'admin');\n")

                # 4. Peak (10:00 - 14:00)
                kwh = round(random.uniform(40, 60) * efficiency, 2)
                cost = round(kwh * price_map['peak'], 2)
                dev_day_total += kwh
                write_sql(f"INSERT INTO `electricity_data_item` (`device_id`, `data_time`, `type`, `begin_time`, `end_time`, `value`, `cost`, `price`, `remark`, `create_time`, `create_by`) VALUES ('{dev['id']}', '{date_str} 11:00:00', 'peak', '{date_str} 10:00:00', '{date_str} 14:00:00', {kwh}, {cost}, {price_map['peak']}, 'AutoGeneratedTest', NOW(), 'admin');\n")

                # 5. Sharp (Old 'sharp', now 'tip') (12:00 - 14:00)
                kwh = round(random.uniform(15, 25) * efficiency, 2)
                cost = round(kwh * price_map['tip'], 2)
                dev_day_total += kwh
                write_sql(f"INSERT INTO `electricity_data_item` (`device_id`, `data_time`, `type`, `begin_time`, `end_time`, `value`, `cost`, `price`, `remark`, `create_time`, `create_by`) VALUES ('{dev['id']}', '{date_str} 13:00:00', 'tip', '{date_str} 12:00:00', '{date_str} 14:00:00', {kwh}, {cost}, {price_map['tip']}, 'AutoGeneratedTest', NOW(), 'admin');\n")

                # Accumulate Monthly/Yearly totals
                key_m = (dev['id'], year_month)
                monthly_data[key_m] = monthly_data.get(key_m, 0.0) + dev_day_total
                
                key_y = (dev['id'], year_str)
                yearly_data[key_y] = yearly_data.get(key_y, 0.0) + dev_day_total
                
                # Insert Daily Aggregate into `data_item` table
                write_sql(f"INSERT INTO `data_item` (`device_id`, `time_code`, `time_type`, `data_time`, `begin_time`, `end_time`, `value`, `remark`, `create_time`, `create_by`) VALUES ('{dev['id']}', '{date_str}', 'DAY', '{date_str} 00:00:00', '{date_str} 00:00:00', '{date_str} 23:59:59', {dev_day_total}, 'AutoGeneratedTest', NOW(), 'admin');\n")

                # Insert Hourly Aggregate (Split day totals into mockup hourly data for the Loop Chart)
                # Strategy: divide day total by 10 active hours (8am-6pm) roughly
                # Simplified: Create one record per hour from 06 to 19
                avg_hourly = dev_day_total / 14.0
                for h in range(6, 20):
                     # Add some random variation
                     val_h = round(avg_hourly * random.uniform(0.8, 1.2), 2)
                     time_str = f"{date_str} {h:02d}:00:00"
                     # Use REPLACE INTO to avoid duplicates if run multiple times? No, clean DB first.
                     write_sql(f"INSERT INTO `data_item` (`device_id`, `time_code`, `time_type`, `data_time`, `begin_time`, `end_time`, `value`, `remark`, `create_time`, `create_by`) VALUES ('{dev['id']}', '{time_str}', 'HOUR', '{time_str}', '{time_str}', '{time_str}', {val_h}, 'AutoGeneratedTest', NOW(), 'admin');\n")

        # Insert Aggregated Monthly Data into `data_item`
        write_sql("\n-- Insert Monthly Aggregates\n")
        for (dev_id, ym), val in monthly_data.items():
            # time_code = '2025-01', time_type = 'MONTH'
            dt = f"{ym}-01 00:00:00"
            write_sql(f"INSERT INTO `data_item` (`device_id`, `time_code`, `time_type`, `data_time`, `begin_time`, `end_time`, `value`, `remark`, `create_time`, `create_by`) VALUES ('{dev_id}', '{ym}', 'MONTH', '{dt}', '{dt}', '{dt}', {round(val, 2)}, 'AutoGeneratedTest', NOW(), 'admin');\n")

        # Insert Aggregated Yearly Data into `data_item`
        write_sql("\n-- Insert Yearly Aggregates\n")
        for (dev_id, y), val in yearly_data.items():
            # time_code = '2025', time_type = 'YEAR'
            dt = f"{y}-01-01 00:00:00"
            write_sql(f"INSERT INTO `data_item` (`device_id`, `time_code`, `time_type`, `data_time`, `begin_time`, `end_time`, `value`, `remark`, `create_time`, `create_by`) VALUES ('{dev_id}', '{y}', 'YEAR', '{dt}', '{dt}', '{dt}', {round(val, 2)}, 'AutoGeneratedTest', NOW(), 'admin');\n")

        # 4.5 Alarms (realistic density + alarm-only SQL)
        write_sql("-- Insert Alarms\n")
        write_alarm_sql("SET NAMES utf8mb4;\n")
        write_alarm_sql("DELETE FROM `alarm` WHERE `remark` = 'AutoGeneratedTest';\n")
        write_alarm_sql("-- Insert realistic alarms\n")

        alarm_catalog = [
            {'err_code': 'E001', 'desc': 'Inverter Grid Voltage High', 'solution': 'Check inverter input voltage and grid parameters', 'level': 1},
            {'err_code': 'E002', 'desc': 'Inverter Temperature High', 'solution': 'Check cooling path and ambient temperature', 'level': 2},
            {'err_code': 'W001', 'desc': 'Communication Interruption', 'solution': 'Check collector and network link', 'level': 3},
            {'err_code': 'W002', 'desc': 'String current mismatch', 'solution': 'Check string wiring and connector condition', 'level': 2},
            {'err_code': 'W003', 'desc': 'Insulation resistance low', 'solution': 'Check insulation and moisture ingress', 'level': 1},
        ]

        # 工作日略高、周末略低；整体保持“每天少量告警”
        daily_count_weights_weekday = [0, 1, 2, 3, 4, 5, 6, 7, 8]
        daily_count_probs_weekday = [0.04, 0.08, 0.13, 0.18, 0.20, 0.16, 0.11, 0.07, 0.03]
        daily_count_weights_weekend = [0, 1, 2, 3, 4, 5, 6]
        daily_count_probs_weekend = [0.08, 0.14, 0.20, 0.22, 0.17, 0.12, 0.07]

        alarm_counter = 1
        device_codes = [d['code'] for d in devices]

        for day_offset in range(total_days):
            current_date = start_date + datetime.timedelta(days=day_offset)
            date_str = current_date.strftime('%Y-%m-%d')
            is_weekend = current_date.weekday() >= 5

            if is_weekend:
                daily_count = random.choices(daily_count_weights_weekend, weights=daily_count_probs_weekend, k=1)[0]
            else:
                daily_count = random.choices(daily_count_weights_weekday, weights=daily_count_probs_weekday, k=1)[0]

            # 保证最新一天可见且不夸张
            if current_date.date() == target_end_date.date():
                daily_count = max(4, min(daily_count, 12))

            used_keys = set()
            for _ in range(daily_count):
                tpl = random.choice(alarm_catalog)
                dev_code = random.choice(device_codes)

                hour = random.randint(8, 20)
                minute = random.randint(0, 59)
                sec = random.randint(0, 59)
                alarm_time = datetime.datetime(current_date.year, current_date.month, current_date.day, hour, minute, sec)
                alarm_time_str = alarm_time.strftime('%Y-%m-%d %H:%M:%S')
                time_code = alarm_time.strftime('%Y%m%d%H%M')

                unique_key = (time_code, dev_code, tpl['err_code'])
                if unique_key in used_keys:
                    continue
                used_keys.add(unique_key)

                # 未处理占比较高，贴近实际现场
                status = '1' if random.random() < 0.72 else '2'

                alarm_id = f"ALARM-{alarm_counter:08d}"
                alarm_counter += 1

                insert_sql = (
                    f"INSERT INTO `alarm` (`id`, `time_code`, `data_time`, `device_code`, `err_code`, `error_description`, `solution`, `level`, `status`, `remark`, `create_time`, `create_by`) "
                    f"VALUES ('{alarm_id}', '{time_code}', '{alarm_time_str}', '{dev_code}', '{tpl['err_code']}', '{tpl['desc']}', '{tpl['solution']}', {tpl['level']}, '{status}', 'AutoGeneratedTest', NOW(), 'admin');\n"
                )
                write_sql(insert_sql)
                write_alarm_sql(insert_sql)


if __name__ == "__main__":
    generate_sql()
    print("Done generating SQL.")
