SET NAMES utf8mb4;

-- 1) 补齐设备类型测点模板（用于实时监测展示）
INSERT INTO device_type_index_template(id, device_type_id, device_type_name, name, code, index_type, unit, remark, create_time, create_by, tag_key)
SELECT UUID(), 'dt-demo-inv', '逆变器', t.name, t.code, 'COLLECT', t.unit, 'AutoGeneratedBaseConfig', NOW(), 'admin', t.tag_key
FROM (
  SELECT '总有功功率' AS name, 'PW' AS code, 'kW' AS unit, 'PW' AS tag_key UNION ALL
  SELECT '功率因数', 'Q', '', 'Q' UNION ALL
  SELECT '频率', 'HZ', 'Hz', 'HZ' UNION ALL
  SELECT 'A相电压', 'UA', 'V', 'UA' UNION ALL
  SELECT 'B相电压', 'UB', 'V', 'UB' UNION ALL
  SELECT 'C相电压', 'UC', 'V', 'UC' UNION ALL
  SELECT 'A相电流', 'IA', 'A', 'IA' UNION ALL
  SELECT 'B相电流', 'IB', 'A', 'IB' UNION ALL
  SELECT 'C相电流', 'IC', 'A', 'IC' UNION ALL
  SELECT '实时发电功率', 'IE', 'kW', 'IE' UNION ALL
  SELECT '累计发电量', 'CGL', 'kWh', 'CGL'
) t
WHERE NOT EXISTS (
  SELECT 1 FROM device_type_index_template d
  WHERE d.device_type_id='dt-demo-inv' AND d.code=t.code
);

-- 2) 给每个演示设备生成 device_index 映射
INSERT INTO device_index(id, index_id, device_id, index_name, index_code, index_type, calc_index, factor, tag_key, unit, remark, create_time, create_by)
SELECT UUID(), dt.id, d.id, dt.name, CONCAT(d.code, '_', dt.code), dt.index_type, '', 1, dt.tag_key, dt.unit, 'AutoGeneratedBaseConfig', NOW(), 'admin'
FROM device d
JOIN device_type_index_template dt ON dt.device_type_id='dt-demo-inv'
LEFT JOIN device_index di ON di.device_id=d.id AND di.index_id=dt.id
WHERE d.id LIKE 'dev-demo-%' AND di.id IS NULL;

-- 3) 补齐尖峰平谷时段配置（用于尖峰报表）
INSERT INTO electricity_type_setting(id, begin_time, end_time, remark, create_time, create_by)
SELECT 'ets-demo-001', '2025-01-01', '2026-12-31', 'AutoGeneratedBaseConfig', NOW(), 'admin'
WHERE NOT EXISTS (SELECT 1 FROM electricity_type_setting WHERE id='ets-demo-001');

INSERT INTO electricity_type_setting_item(id, parent_id, type, begin_time, end_time, electricity_price, remark, create_time, create_by)
SELECT UUID(), 'ets-demo-001', x.type, x.begin_time, x.end_time, x.price, 'AutoGeneratedBaseConfig', NOW(), 'admin'
FROM (
  SELECT 'deep' AS type, '00:00:00' AS begin_time, '06:00:00' AS end_time, 0.20 AS price UNION ALL
  SELECT 'trough', '06:00:00', '08:00:00', 0.40 UNION ALL
  SELECT 'flat', '08:00:00', '10:00:00', 0.80 UNION ALL
  SELECT 'peak', '10:00:00', '12:00:00', 1.20 UNION ALL
  SELECT 'tip', '12:00:00', '14:00:00', 1.50 UNION ALL
  SELECT 'peak', '14:00:00', '16:00:00', 1.20 UNION ALL
  SELECT 'flat', '16:00:00', '18:00:00', 0.80 UNION ALL
  SELECT 'trough', '18:00:00', '22:00:00', 0.40 UNION ALL
  SELECT 'deep', '22:00:00', '23:59:59', 0.20
) x
WHERE NOT EXISTS (
  SELECT 1 FROM electricity_type_setting_item i
  WHERE i.parent_id='ets-demo-001' AND i.type=x.type AND i.begin_time=x.begin_time AND i.end_time=x.end_time
);
