-- 补齐报警 mock 数据到 2026-03-31（兼容 MySQL 5.7）
-- 用法：在目标库执行本文件。
-- 说明：
-- 1) 仅清理本脚本生成的数据（remark='AutoGeneratedAlarm0331'）。
-- 2) 按 device 表中现有设备批量生成 2026-03-01 ~ 2026-03-31 报警。
-- 3) level 使用整数 1/2/3，符合后端统计逻辑。

SET NAMES utf8mb4;

-- 可重复执行：先删本脚本历史生成数据
DELETE FROM alarm WHERE remark = 'AutoGeneratedAlarm0331';

-- 生成 31 天数字表（0~30）
-- 注：为兼容 MySQL 5.7，使用 UNION ALL，不使用递归 CTE

-- 一级报警（事故，未处理）
INSERT IGNORE INTO alarm (
  id,
  time_code,
  data_time,
  device_code,
  err_code,
  error_description,
  solution,
  level,
  status,
  handlers,
  handlers_name,
  processing_time,
  remark,
  create_time,
  create_by,
  update_time,
  update_by,
  image_url
)
SELECT
  REPLACE(UUID(), '-', '') AS id,
  DATE_FORMAT(DATE_ADD('2026-03-01 09:10:00', INTERVAL d.day_offset DAY), '%Y%m%d%H%i') AS time_code,
  DATE_ADD('2026-03-01 09:10:00', INTERVAL d.day_offset DAY) AS data_time,
  dv.code AS device_code,
  'E001' AS err_code,
  '逆变器电压过高' AS error_description,
  '检查逆变器输入电压及并网参数' AS solution,
  1 AS level,
  '1' AS status,
  NULL,
  NULL,
  NULL,
  'AutoGeneratedAlarm0331' AS remark,
  NOW() AS create_time,
  'admin' AS create_by,
  NOW() AS update_time,
  'admin' AS update_by,
  NULL AS image_url
FROM device dv
JOIN (
  SELECT 0 AS day_offset UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
  UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9
  UNION ALL SELECT 10 UNION ALL SELECT 11 UNION ALL SELECT 12 UNION ALL SELECT 13 UNION ALL SELECT 14
  UNION ALL SELECT 15 UNION ALL SELECT 16 UNION ALL SELECT 17 UNION ALL SELECT 18 UNION ALL SELECT 19
  UNION ALL SELECT 20 UNION ALL SELECT 21 UNION ALL SELECT 22 UNION ALL SELECT 23 UNION ALL SELECT 24
  UNION ALL SELECT 25 UNION ALL SELECT 26 UNION ALL SELECT 27 UNION ALL SELECT 28 UNION ALL SELECT 29
  UNION ALL SELECT 30
) d
WHERE dv.code IS NOT NULL AND dv.code <> '';

-- 二级报警（严重，已处理）
INSERT IGNORE INTO alarm (
  id,
  time_code,
  data_time,
  device_code,
  err_code,
  error_description,
  solution,
  level,
  status,
  handlers,
  handlers_name,
  processing_time,
  remark,
  create_time,
  create_by,
  update_time,
  update_by,
  image_url
)
SELECT
  REPLACE(UUID(), '-', '') AS id,
  DATE_FORMAT(DATE_ADD('2026-03-01 13:20:00', INTERVAL d.day_offset DAY), '%Y%m%d%H%i') AS time_code,
  DATE_ADD('2026-03-01 13:20:00', INTERVAL d.day_offset DAY) AS data_time,
  dv.code AS device_code,
  'E002' AS err_code,
  '逆变器温度过高' AS error_description,
  '检查散热风道与环境温度' AS solution,
  2 AS level,
  '2' AS status,
  '1' AS handlers,
  'admin' AS handlers_name,
  DATE_ADD('2026-03-01 15:00:00', INTERVAL d.day_offset DAY) AS processing_time,
  'AutoGeneratedAlarm0331' AS remark,
  NOW() AS create_time,
  'admin' AS create_by,
  NOW() AS update_time,
  'admin' AS update_by,
  NULL AS image_url
FROM device dv
JOIN (
  SELECT 0 AS day_offset UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
  UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9
  UNION ALL SELECT 10 UNION ALL SELECT 11 UNION ALL SELECT 12 UNION ALL SELECT 13 UNION ALL SELECT 14
  UNION ALL SELECT 15 UNION ALL SELECT 16 UNION ALL SELECT 17 UNION ALL SELECT 18 UNION ALL SELECT 19
  UNION ALL SELECT 20 UNION ALL SELECT 21 UNION ALL SELECT 22 UNION ALL SELECT 23 UNION ALL SELECT 24
  UNION ALL SELECT 25 UNION ALL SELECT 26 UNION ALL SELECT 27 UNION ALL SELECT 28 UNION ALL SELECT 29
  UNION ALL SELECT 30
) d
WHERE dv.code IS NOT NULL AND dv.code <> '';

-- 三级报警（普通，未处理）
INSERT IGNORE INTO alarm (
  id,
  time_code,
  data_time,
  device_code,
  err_code,
  error_description,
  solution,
  level,
  status,
  handlers,
  handlers_name,
  processing_time,
  remark,
  create_time,
  create_by,
  update_time,
  update_by,
  image_url
)
SELECT
  REPLACE(UUID(), '-', '') AS id,
  DATE_FORMAT(DATE_ADD('2026-03-01 18:30:00', INTERVAL d.day_offset DAY), '%Y%m%d%H%i') AS time_code,
  DATE_ADD('2026-03-01 18:30:00', INTERVAL d.day_offset DAY) AS data_time,
  dv.code AS device_code,
  'W001' AS err_code,
  '通讯中断告警' AS error_description,
  '检查采集器与网络连接' AS solution,
  3 AS level,
  '1' AS status,
  NULL,
  NULL,
  NULL,
  'AutoGeneratedAlarm0331' AS remark,
  NOW() AS create_time,
  'admin' AS create_by,
  NOW() AS update_time,
  'admin' AS update_by,
  NULL AS image_url
FROM device dv
JOIN (
  SELECT 0 AS day_offset UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
  UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9
  UNION ALL SELECT 10 UNION ALL SELECT 11 UNION ALL SELECT 12 UNION ALL SELECT 13 UNION ALL SELECT 14
  UNION ALL SELECT 15 UNION ALL SELECT 16 UNION ALL SELECT 17 UNION ALL SELECT 18 UNION ALL SELECT 19
  UNION ALL SELECT 20 UNION ALL SELECT 21 UNION ALL SELECT 22 UNION ALL SELECT 23 UNION ALL SELECT 24
  UNION ALL SELECT 25 UNION ALL SELECT 26 UNION ALL SELECT 27 UNION ALL SELECT 28 UNION ALL SELECT 29
  UNION ALL SELECT 30
) d
WHERE dv.code IS NOT NULL AND dv.code <> '';

-- 快速自检
SELECT
  MIN(data_time) AS min_time,
  MAX(data_time) AS max_time,
  COUNT(*) AS total_count,
  SUM(CASE WHEN status = '1' THEN 1 ELSE 0 END) AS unprocessed_count,
  SUM(CASE WHEN status = '2' THEN 1 ELSE 0 END) AS processed_count,
  SUM(CASE WHEN level = 1 THEN 1 ELSE 0 END) AS level1_count,
  SUM(CASE WHEN level = 2 THEN 1 ELSE 0 END) AS level2_count,
  SUM(CASE WHEN level = 3 THEN 1 ELSE 0 END) AS level3_count
FROM alarm
WHERE remark = 'AutoGeneratedAlarm0331';
